name: ${GLOBAL_NAME}

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      TZ: ${TIMEZONE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - default:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

  shlink:
    container_name: ${SHLINK_CONTAINER_NAME}
    image: ${SHLINK_IMAGE_NAME}:${SHLINK_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
      DEFAULT_DOMAIN: ${DDNS_ADDR}
      SHORT_DOMAIN_HOST: ${DDNS_ADDR}
      SHORT_DOMAIN_SCHEMA: ${SHORT_DOMAIN_SCHEMA}
      BASE_URL: ${SHLINK_APP_URL}:${SHLINK_HTTP_PORT}
      IS_HTTPS_ENABLED: ${IS_HTTPS_ENABLED}
      SHELL_VERBOSITY: ${SHELL_VERBOSITY}
      TZ: ${TIMEZONE}
    ports:
      - "${SHLINK_HTTP_PORT}:8080"
    volumes:
      - shlink_data:/var/www/html/data
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  shlink_web:
    container_name: ${SHLINK_WEB_CONTAINER_NAME}
    image: ${SHLINK_WEB_IMAGE_NAME}:${SHLINK_WEB_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      SHLINK_SERVER_URL: ${SHLINK_APP_URL}:${SHLINK_HTTP_PORT}
      SHLINK_SERVER_API_KEY: ${SHLINK_API_KEY}
      TZ: ${TIMEZONE}
    ports:
      - "${SHLINK_WEB_HTTP_PORT}:80"
      - "${SHLINK_WEB_HTTPS_PORT}:443"
    networks:
      - default
    depends_on:
      - shlink

networks:
  default:
    name: ${SHLINK_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${POSTGRES_CONTAINER_NAME}_data
    driver: local
  shlink_data:
    name: ${SHLINK_CONTAINER_NAME}_data
    driver: local